#!/bin/bash

if [ $# -ne 1 ]
then
	echo "Usage: $(basename $0) file"
	exit 1
fi

# "/Users/truongnm/coding/cnn/DeepECG/raw/04015.png"
FILE_PATH=$1
FILE_NAME=$(basename -- "$FILE_PATH")
EXTENSION="${FILE_NAME##*.}"
FILE_NAME_WITHOUT_EXT="${FILE_NAME%%.*}"
OUTPUT_DIR=$(dirname "${FILE_PATH}")
# echo "FILE_PATH: ${FILE_PATH}"
# echo "FILE_NAME: ${FILE_NAME}"
# echo "EXTENSION: ${EXTENSION}"
# echo "FILE_NAME_WITHOUT_EXT: ${FILE_NAME_WITHOUT_EXT}"
# echo "OUTPUT_DIR: ${OUTPUT_DIR}"

python img2csv.py ${FILE_PATH}
wrsamp -i raw/${FILE_NAME_WITHOUT_EXT}-from-user.csv -o raw/${FILE_NAME_WITHOUT_EXT}-from-user -G 1000 -F 300 -z
wfdb2mat -r raw/${FILE_NAME_WITHOUT_EXT}-from-user > /dev/null
python predict.py "${FILE_NAME_WITHOUT_EXT}-from-userm.mat"
